#!/bin/sh

xrdb -merge ~/.Xresources

# Refresh rate of the keyboard
xset r rate 150 75

# Where play, stop, volume buttons gets to bind
xbindkeys

# Reset volume to 50%
pamixer --set-volume 50

# Enable system wide natural scrolling (Yes, please!)
xinput set-prop 9 289 1
xinput set-prop 9 290 1

layout

spotifyd

export _JAVA_AWT_WM_NONREPARENTING=1

exec dwm
