local opt = vim.opt
local g = vim.g

g.mapleader = " "
g.maplocalLeader = "\\"
g.loaded_netrw = 0
g.loaded_netrwPlugin = 0

opt.swapfile = false
opt.incsearch = false
opt.hlsearch = false
opt.cursorline = false
opt.ruler = false
opt.termguicolors = true
opt.clipboard = "unnamedplus"
opt.completeopt = { "menu", "menuone", "noselect", "fuzzy" }
opt.expandtab = true
opt.fillchars = {
  foldopen = "",
  foldclose = "",
  fold = " ",
  foldsep = " ",
  diff = "╱",
  eob = " ",
}
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --vimgrep"
opt.ignorecase = true
opt.smartcase = true
opt.jumpoptions = "view"
opt.laststatus = 0
opt.linebreak = true
opt.list = true
opt.pumheight = 10
opt.scrolloff = 8
opt.sidescrolloff = 512
opt.shiftround = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.shortmess = "mrsIcCWFt"
opt.showmode = false
opt.signcolumn = "yes"
opt.spelllang = { "en_us" }
opt.splitbelow = true
opt.splitright = true
opt.splitkeep = "screen"
opt.undofile = true
opt.undolevels = 4096
opt.virtualedit = "block"
opt.wildmode = "longest:full,full"
opt.softtabstop = 2
