#!/usr/bin/python

import os
import sys
import shutil

def assert_exists(path: str):
    target = os.path.join(os.path.expanduser("~"), path)

    if not os.path.isdir(target):
        sys.exit(f"❌{target} appears to be missing")

    return target

src = assert_exists(".config/nvim")
dst = assert_exists("code/my/dotfiles")

print(f"✓ found dotfiles at {dst}")
print(f"✓ found nvim config at {src}")

shutil.rmtree(os.path.join(dst, "files/linux/nvim"), ignore_errors=True)

shutil.copytree(
    src,
    os.path.join(dst, "files/linux/nvim"),
    ignore=shutil.ignore_patterns("site", "plugin")
)

print("✓ copied nvim config to dotfiles")
