#!/usr/bin/python

import os
import sys
import shutil
from typing import Dict

dest = os.path.join(os.path.expanduser("~"), "code/my/dotfiles")
src = os.path.join(os.path.expanduser("~"), ".config/nvim")

if not os.path.isdir(dest):
    sys.exit(f"❌dotfiles does not exists, tried {dest}")

print(f"✓ found dotfiles at {dest}")

if not os.path.isdir(src):
    sys.exit(f"❌could not find nvim config, tried {src}")

print(f"✓ found nvim config at {src}")

shutil.rmtree(os.path.join(dest, "files/linux/nvim"), ignore_errors=True)

shutil.copytree(
    src,
    os.path.join(dest, "files/linux/nvim"),
    ignore=shutil.ignore_patterns("site", "plugin")
)

print("✓ copied nvim to dotfiles")
