#!/bin/env bash

curl -s "https://archlinux.org/mirrorlist/?country=EE&country=FI&protocol=https&use_mirror_status=on" \
  | sed -e 's/^#Server/Server/' -e '/^#/d' \
  | rankmirrors -n 10 - \
  > /tmp/new-mirrorlist

sudo mv /tmp/new-mirrorlist /etc/pacman.d/mirrorlist
