#!/usr/bin/python

import sys
import webbrowser
from urllib.parse import urlencode

def main():
    args = sys.argv[1:]

    if len(args) == 0: 
        return

    opts = {
        "q": " ".join(args),
    }

    uri = "https://duckduckgo.com?" + urlencode(opts)
    webbrowser.open_new_tab(uri)

main()
