return {
  "nvim-treesitter/nvim-treesitter",
  commit = "01ced7499fb07f6c94abd316414ef198bd6e7058",
  run = ":TSUpdate",
  config = function()
    require("nvim-treesitter").setup()

    require("nvim-treesitter").install({
      "astro",
      "bash",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "desktop",
      "diff",
      "dockerfile",
      "editorconfig",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "glsl",
      "go",
      "gpg",
      "graphql",
      "hlsl",
      "html",
      "htmldjango",
      "http",
      "hyprlang",
      "ini",
      "java",
      "javadoc",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "kitty",
      "liquid",
      "llvm",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "mermaid",
      "nginx",
      "ninja",
      "objc",
      "objdump",
      "passwd",
      "pug",
      "pymanifest",
      "python",
      "rasi",
      "requirements",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "superhtml",
      "svelte",
      "swift",
      "terraform",
      "tmux",
      "toml",
      "tsx",
      "twig",
      "typescript",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
    })

    vim.api.nvim_create_autocmd({ "BufEnter", "BufWinEnter" }, {
      pattern = "*",
      callback = function()
        pcall(vim.treesitter.start)
      end,
    })
  end,
}
